MicrobiomeDB terms needed for EDA
VEuPathDB-ontology/VEuPathDB-ontology pull request #219
Opened 2021-06-25 20:50 UTC by johnwjudkins

Closes #208

2021-06-28 14:35 UTC, zhengj2007 reviewed
Better to add 'Definition source' and "Term editor' annotation properties.

The data item term mentioned is output of some analysis in the textual definition. Would add it in logical axiom as well.

2021-06-28 19:43 UTC, cstoeckert reviewed
I agree with Jie's comments.

2021-07-06 15:21 UTC, zhengj2007 requested changes
EUPATH_0009259 Shannon-indexed alpha diversity data
Definition: 
a alpha diversity taxonomic analysis -> an alpha diversity taxonomic analysis

EUPATH_0009260 inverse Simpson-indexed alpha diversity data
Definition: 
a alpha diversity taxonomic analysis -> an alpha diversity taxonomic analysis

EUPATH_0009248 metagenome enzyme pathway abundance data
Not specify logic axiom:
	is_specified_output_of some ‘metagenome pathway and function analysis’

EUPATH_0009249 metagenome enzyme pathway coverage data
Not specify logic axiom:
	is_specified_output_of some ‘metagenome pathway and function analysis’

2021-07-07 20:37 UTC, cstoeckert approved these changes

2021-07-08 13:27 UTC, zhengj2007 approved these changes

2021-07-09 18:21 UTC, merged