Adds administrative region terms
VEuPathDB-ontology/VEuPathDB-ontology pull request #253
Opened 2021-11-18 20:30 UTC by johnwjudkins

Closes #243. This adds the new administrative region terms and restores part of the ENVO import hiearchy to match ENVO, i.e.
'site' > 'administrative region'
instead of
'site' > 'geographic location' > 'administrative region'.

2021-11-18 21:06 UTC, cstoeckert requested changes
The definitions of EUPATH_0044179 and EUPATH_0038723 look wrong (they're about Tanzania and the labels are not).

2021-11-19 14:50 UTC, cstoeckert approved these changes

2021-11-19 14:58 UTC, zhengj2007 requested changes
Removed import of the term:
http://purl.obolibrary.org/obo/ENVO_01000254 #environmental system
However, a couple of terms are subClasses of it. So, it ends there is ENVO_01000254 shown under owl:Thing.

Should EUPATH_0028020 'parish of Uganda' be subClass of ENVO_00000008 'fourth-order administrative region'?

Definition source of term 'district of India' should be VEuPathDB

2021-11-19 18:41 UTC, zhengj2007 commented
May send request to ENVO for 'fifth-order administrative region'.

2021-11-19 18:41 UTC, zhengj2007 approved these changes

2021-11-24 15:19 UTC, merged