Makefile changes to list new VEuPath terms and new import terms
VEuPathDB-ontology/VEuPathDB-ontology pull request #361
Opened 2022-06-15 13:49 UTC by johnwjudkins

#358. The next step is to work on automation for the release notes themselves.

2022-06-15 18:02 UTC, zhengj2007 requested changes
Cannot run through all Make command because got this error: 'make: *** [verify-entities] Error 1'

The new-terms.tsv does not only listed the newly added terms. It includes the terms that labels changed. So, the number of new terms is not correct. Can consider to only list term IDs in previous release and current release. Then append the labels to the newly added term list.

2022-06-17 18:06 UTC, johnwjudkins commented
The Makefile now creates new-terms.tsv and new-imports.tsv, which list the IRIs and labels for VEuPath terms and import terms, respectively, that have been added since the previous release. This can be tested by adding temporary terms to eupath-dev.owl or an import module.

2022-06-17 19:51 UTC, zhengj2007 requested changes
Since we are going to use new_terms.tsv and new_imports.tsv as part of release notes, it would be better to use ID rather than IRI and string of labels without language settings.

2022-06-22 13:37 UTC, zhengj2007 approved these changes

2022-06-22 13:42 UTC, merged