add 'information on putatively essential gene'
VEuPathDB-ontology/VEuPathDB-ontology pull request #373
Opened 2022-07-11 14:26 UTC by johnwjudkins

Closes #367. Using this label because we decided to create this term as an ICE.

2022-07-12 19:17 UTC, zhengj2007 requested changes
Since the parent is 'conclusion based on data', can you change the definition starting with 'A conclusion based on data' rather than 'An information content entity'? Thanks.

2022-07-14 17:38 UTC, johnwjudkins commented
Also changed label to include "conclusion".

2022-07-15 20:03 UTC, zhengj2007 requested changes
keep the label as 'information on putatively essential gene'
alternative label is: 'inferred essential, putatively lethal'
VEuPathDB alternative label: 'putatively essential'

2022-07-18 21:18 UTC, zhengj2007 approved these changes

2022-07-19 13:13 UTC, merged