add 'eukaryote detection and abundance analysis'
VEuPathDB-ontology/VEuPathDB-ontology pull request #395
Opened 2022-08-30 20:27 UTC by johnwjudkins

Closes #392.

2022-08-30 20:31 UTC, johnwjudkins commented
Since the definition refers to CORALE software, I changed the label.

2022-08-30 20:40 UTC, asizemore requested changes
In general looks great to me! But worth getting approval from Dan on wording specifics before merging.

2022-08-30 20:40 UTC, asizemore commented on src/ontology/eupath_dev.owl
> +        <obo:IAO_0000115>A data transformation that uses data from a whole metagenome sequencing assay and CORALE (for Clustering of Reference Alignments) software to specify taxa of Eukaryota in a s
```suggestion
        <obo:IAO_0000115>A data transformation that uses data from a whole metagenome sequencing assay and CORRAL (for Clustering of Reference Alignments) software to specify taxa of Eukaryota in a specimen.</obo:IAO_0000115>
```

2022-08-30 20:40 UTC, asizemore commented on src/ontology/eupath_dev.owl
> +        <rdfs:label>eukaryote detection and abundance analysis using CORALE software</rdfs:label>
```suggestion
        <rdfs:label>eukaryote detection and abundance analysis using CORRAL software</rdfs:label>
```

2022-09-08 13:31 UTC, asizemore commented
Sorry just realized i left the same comments here and in the issue. But i just spoke with Dan and he also thought it's great after the CORALE -> CORRAL changes! Thanks so much @johnwjudkins !

2022-09-08 16:19 UTC, johnwjudkins commented
I see the most recent version of the article reads "CORRAL". I changed the label & definition.

2022-09-08 16:28 UTC, asizemore approved these changes
Thanks @johnwjudkins ! 
I apologize I missed a related change from the CORALE -> CORRAL switch in the paper. I put that in as a requested change but otherwise looks great!

2022-09-08 16:28 UTC, asizemore commented on src/ontology/eupath_dev.owl
> +        <obo:IAO_0000115>A data transformation that uses data from a whole metagenome sequencing assay and CORRAL (for Clustering of Reference Alignments) software to specify taxa of Eukaryota in a s
```suggestion
        <obo:IAO_0000115>A data transformation that uses data from a whole metagenome sequencing assay and CORRAL (for Clustering Of Related Reference ALignments) software to specify taxa of Eukaryota in a specimen.</obo:IAO_0000115>
```

2022-09-08 16:28 UTC, asizemore commented on src/ontology/eupath_dev.owl
> +        <obo:IAO_0000115>A data transformation that uses data from a whole metagenome sequencing assay and CORRAL (for Clustering of Reference Alignments) software to specify taxa of Eukaryota in a s
(for reference, the above change was just copied from the [paper](https://www.biorxiv.org/content/10.1101/2022.03.09.483664v2))

2022-09-08 16:56 UTC, zhengj2007 approved these changes

2022-09-12 19:03 UTC, merged